import { Response } from 'express';
import { AuthRequest, OrderStatus, PaymentMethod } from '../types';
import Order from '../models/Order.model';
import Cart from '../models/Cart.model';
import { asyncHandler, AppError } from '../middleware/error.middleware';

// @desc    Create new order (Checkout)
// @route   POST /api/orders
// @access  Private
export const createOrder = asyncHandler(async (req: AuthRequest, res: Response) => {
  const { shippingAddress, paymentMethod, notes } = req.body;

  // 1. Get user's cart
  const cart = await Cart.findOne({ user: req.user!._id });
  if (!cart || cart.items.length === 0) {
    throw new AppError('Cart is empty', 400);
  }

  // 2. Create Order
  const order = await Order.create({
    user: req.user!._id,
    items: cart.items,
    totalAmount: cart.totalAmount,
    shippingAddress,
    paymentMethod,
    notes,
    orderNumber: 'TEMP', // Will be auto-generated by pre-save
  });

  // 3. Simulate M-Pesa Trigger (Real integration comes later)
  if (paymentMethod === PaymentMethod.MPESA) {
    console.log(`📲 Simulating M-Pesa STK Push to ${req.user!.phone} for KES ${order.totalAmount}`);
    // In real app, we would call mpesaService.stkPush() here
  }

  // 4. Clear Cart
  await cart.clearCart();

  res.status(201).json({ success: true, message: 'Order created', data: order });
});
