// src/types/index.ts (Refactored for Prisma)

/**
 * TypeScript Type Definitions
 * * This file contains custom types and interfaces used throughout the backend,
 * tailored to work alongside the types generated by the Prisma Client.
 */

import { Request } from 'express';
// We remove the Mongoose 'Document' import: import { Document } from 'mongoose';

// Import all Prisma Models/Enums for use in our custom types
import {
  User as PrismaUser,
  Product as PrismaProduct,
  Order as PrismaOrder,
  UserRole as PrismaUserRole,
  ProductCategory as PrismaProductCategory,
  ServiceType as PrismaServiceType,
  OrderStatus as PrismaOrderStatus,
  PaymentMethod as PrismaPaymentMethod,
} from '@prisma/client';

// ------------------------------------------------------------------
// 1. Core Enums (Re-exporting Prisma Enums for convenience)
// ------------------------------------------------------------------

export const UserRole = PrismaUserRole;
export type UserRole = PrismaUserRole;

export const ProductCategory = PrismaProductCategory;
export type ProductCategory = PrismaProductCategory;

export const ServiceType = PrismaServiceType;
export type ServiceType = PrismaServiceType;

export const OrderStatus = PrismaOrderStatus;
export type OrderStatus = PrismaOrderStatus;

export const PaymentMethod = PrismaPaymentMethod;
export type PaymentMethod = PrismaPaymentMethod;

// ------------------------------------------------------------------
// 2. Core Interfaces (Using Prisma types where possible)
// ------------------------------------------------------------------

/**
 * User Interface (Prisma Model Type)
 * We extend the Prisma model type to include methods/properties needed by Express.
 */
// The '_id' property is replaced by 'id' in Prisma (mapped from _id in schema.prisma)
export interface IUser extends PrismaUser {
    // Methods are now defined as standalone utility functions, not on the model instance:
    // comparePassword(candidatePassword: string): Promise<boolean>; 
    // generateAuthToken(): string;
}

/**
 * Product Interface (Prisma Model Type)
 */
export interface IProduct extends PrismaProduct {
    // The createdBy field now refers to the Prisma User ID type (string)
    createdBy: string;
}

/**
 * Cart Item Interface
 * * Note: This type is defined as a 'type' in schema.prisma, so we mirror it here.
 */
export interface ICartItem {
  productId: string; // The ID is now a simple string, not IProduct['_id']
  quantity: number;
  size?: string;
  color?: string;
  price: number;
}

/**
 * Cart Interface (Prisma Model Type)
 * * Contains the ICartItem type defined above.
 */
export interface ICart {
    id: string;
    userId: string;
    items: ICartItem[];
    totalAmount: number;
    createdAt: Date;
    updatedAt: Date;
}

/**
 * Order Interface (Prisma Model Type)
 */
export interface IOrder extends PrismaOrder {
    // The methods defined on the Mongoose model must now be implemented 
    // as functions in the order module (e.g., order.service.ts)
}


// ------------------------------------------------------------------
// 3. Specialized Interfaces (Remain largely the same)
// ------------------------------------------------------------------

/**
 * Service Showcase Interface (New model definition required in schema.prisma)
 */
// For now, this remains an interface until you create the Prisma model
export interface IServiceShowcase {
  id: string;
  title: string;
  description: string;
  serviceType: ServiceType;
  images: string[];
  clientName?: string;
  projectUrl?: string;
  technologies: string[];
  duration: string;
  featured: boolean;
  createdAt: Date;
}

/**
 * M-Pesa Callback Data Interface
 */
export interface IMpesaCallback {
  MerchantRequestID: string;
  CheckoutRequestID: string;
  ResultCode: number;
  ResultDesc: string;
  CallbackMetadata?: {
    Item: Array<{
      Name: string;
      Value: string | number;
    }>;
  };
}

/**
 * Extended Express Request Interface
 */
export interface AuthRequest extends Request {
  // The user object retrieved from the token payload and DB will conform to IUser
  user?: IUser;
  file?: Express.Multer.File;
  files?: Express.Multer.File[];
}

/**
 * API Response Interface
 */
export interface ApiResponse<T = any> {
  success: boolean;
  message: string;
  data?: T;
  error?: string;
  pagination?: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
}

/**
 * JWT Payload Interface
 * * The userId is now a simple string (Prisma ID type)
 */
export interface JWTPayload {
  userId: string;
  email: string;
  role: UserRole;
}

/**
 * Query Parameters Interface
 */
export interface QueryParams {
  page?: number;
  limit?: number;
  sort?: string;
  search?: string;
  category?: string;
  minPrice?: number;
  maxPrice?: number;
}